# Default Anaconda ISO configuration for this image.
#
# The kickstart post section switches the installed system to the
# published container image for this repository. If you need to build a
# variant ISO (for example KDE), use one of the sibling files in this
# directory as a starting point (iso-gnome.toml, iso-kde.toml) and update
# the GitHub Action or Just recipe to point at the desired file.

[customizations.installer.kickstart]
contents = """
%post
bootc switch --mutate-in-place --transport registry ghcr.io/joshyorko/dudleys-second-bedroom:latest
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]
